name: Code Quality

on:
  - push

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Run flake8
        uses: julianwachholz/flake8-action@v2
        with:
          checkName: "Python Lint"
          path: ./
          plugins: flake8-spellcheck
          config: setup.cfg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}